### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JulianSpagnuolo** [locklin/gtm#2]
Would it be possible to get a brief outline of the purpose of the various functions, i.e. a quickstart guide?

**Comment by locklin** [comment]
I didn't write it; according to the author, he just translated some sloppy Matlab code into this. I'll likely never do anything with this code. Easier to start over. It's sort of like Kohonen maps.

**Comment by locklin** [comment]
GTM I think was Bishop's idea. Pretty sure folks who were fans of this class of unsupervised models have moved on to whatever the latest hotness is (TSNE seems popular, but it always looked like reading tea leaves to me).
I found the mapper algorithm to have some decent juice if you know how to use it, for unsupervised mapping of data onto graphs (I worked at Ayasdi for a year). Kepler seems to be the best open source version. Not sure if there are any guides to using it; it helps to know a little point topology to pick the right metric and filters.
